### ISSUE TITLE
Lib not working on Windows 

### ISSUE THREAD

**Issue by alanhr** [anam-hossain/phantommagick#13]
Hi guy, your lib is not working on windows however I solved the problem and I'm putting here the part of the code.

Your code 
**elseif (Str::contains($uname, 'win')) {
            if (! shell_exec(escapeshellcmd("where {$binary}"))) {
                return false;
            }**

My code 

 elseif (Str::contains($uname, 'win')) {
            if (! shell_exec(escapeshellcmd("{$binary}"))) {
                return false;
            }

The problem is   in **where**

**Comment by anam-hossain** [comment]
@alanhr can you do a PR. Thanks.

**Comment by alanhr** [comment]
@anam-hossain  ok  :)

**Comment by anam-hossain** [comment]
@alanhr Thanks. Which version of windows are you using? Does this work in: Windows 7 and Windows 10?

Sorry i have no access to a windows machine.

**Comment by alanhr** [comment]
Yes, in both.
I use win 7 in my work , win 10 in my house and linux in my notebook

**Comment by alanhr** [comment]
When to run the code with  **where** in win7/10 show me this exception

> Binary does not exist

**Comment by anam-hossain** [comment]
@alanhr thanks.
