### ISSUE TITLE
Conversion failed

### ISSUE THREAD

**Issue by hrisafis** [anam-hossain/phantommagick#2]
Very nice work but when I try to convert I always get a "Conversion Failed".
Any thoughts?

**Comment by anam-hossain** [comment]
@hrisafis Please share your code. Which OS are you using?

**Comment by hrisafis** [comment]
It's a linux server and the code is
use Anam\PhantomMagick\Converter;
Converter::make('http://google.com')->toPdf()->download('google.pdf');

**Comment by anam-hossain** [comment]
@hrisafis I just tried the same code in Ubuntu and Mac working fine. PhantomMagick uses the `sys_get_temp_dir()` to write temp files in PHP's temp dir. Please ensure that your temp dir is writable.

**Comment by hrisafis** [comment]
/tmp permissions are 755
very strange, is there anything else I should check?

**Comment by hrisafis** [comment]
I added this
if (! touch($this->getTempFilePath())) {
            throw new RuntimeException('Unable to create file in temp directory: '. sys_get_temp_dir());
        }

to public function toPdf(array $options = array())
and now it creates an empty file
It might be something with the temp folder after all, any workaround?

**Comment by anam-hossain** [comment]
Please check your PHP log file for any errors.

are you using die and dump?

When i was developing the PhantomMagick, one strange thing i noticed is, if you use die and dump `phantomjs` does not generate the pdf/image file.

**Comment by hrisafis** [comment]
Only error is conversion failed.
No not using die or dump.

**Comment by DesignofKA** [comment]
I'm in a similar situation to **hrisafis**. 

I am using the lumen framework with homestead on mac osx (homestead uses linux but I may be mistaken). PhantomMagick is able to detect the linux binary file. Using the runtime exception code **hrisafis** added, I receive an automatic download of a blank, unreadable pdf with the given filename.  

I'm not sure if the issue is with the linux binary creating the pdf as I don't think it is file permissions (I did change the tmp folder location to see if it was a permissions problem but that still didn't solve the issue).

**Comment by anam-hossain** [comment]
@DesignofKA which binary do you used? can you give me the binary link and what is your OS version?

I looking for any clue to fix this but found nothing.

**Comment by DesignofKA** [comment]
@anam-hossain I used phantomjs-linux-x86-binary. Using Mavericks 10.9.5.

**Comment by anam-hossain** [comment]
To determine if you are running a 32-bit or 64-bit version of OS X, open a Terminal and type:

```bash
uname -a
```

please post the output here. thanks.

**Comment by DesignofKA** [comment]
Darwin **{computer name}** 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64

**Comment by anam-hossain** [comment]
@DesignofKA  i forgot to mention the homestead. please ssh to homestead and type in terminal:

```bash
uname -a
```

**Comment by DesignofKA** [comment]
@anam-hossain Linux homestead 3.16.-.23-generic #31-Ubuntu SMP Tue Oct 21 17:56:17 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by anam-hossain** [comment]
@DesignofKA I have setup a new Laravel project and pulled `PhantomMagick` and `phantomjs-linux-x86-binary` and tested in both mac and Homestead. working fine in my side.

Do you find any solution?

Can you please composer update from Homestead and see working or not?

**Comment by DesignofKA** [comment]
@anam-hossain Was able to get a pdf when using a new laravel install as you did. Decided to move my project over the laravel. Not sure what caused the issue but I'm sure i'm over looking something. 

Thank you very much for your help.
