### ISSUE TITLE
Some urls have response: Unable to load the address!

### ISSUE THREAD

**Issue by patrickcurl** [anam-hossain/phantommagick#6]
Example: 
Running this via artisan tinker: 
$c = new Anam\PhantomMagick\Converter();
$c->source("http://blossom.co")->toPng()->save('tmp/blossom.png');

Output:
=> """
   size: 1280px\n
   pageHeight: 960\n
   Unable to load the address!\n
   """
-- but if I do google.com it works.. I have a lot of business sites in a directory I'm launching, and trying to seed screenshots of each site. -- But each api/method I've tried so far has had errors or 'misses' on some  domains/urls. I think it could be something with cloudflare/ssl blocking it.

**Comment by pixelgremlins** [comment]
Actually solved the issue, added two flags: --ssl-protocol=any --ignore-ssl-errors=yes in Runner.php (see my pull request)...

**Comment by anam-hossain** [comment]
@pixelgremlins thanks. I will merge them soon.
